### ISSUE TITLE
lng serve opens up Index Of directory page...

### ISSUE THREAD

**Issue by paynetechnologies** [KadeejaBai/Lightning-Tic-Tac-Toe-MinionGame#4]
Hi,

Thanks for your hard work.

I seem to be  missing something. I downloaded the code and when I issue the lng serve command, an Index of page opens. I was expecting to see something related to Tic-Tac-Toe.

Can you clarify what I might be doing wrong?

Thanks,
Howard

![TicTacToe_Minnons_GitHub](https://user-images.githubusercontent.com/628590/79692171-b5016f80-8231-11ea-9945-f6172fa6a461.png)

**Comment by paynetechnologies** [comment]
![TicTacToe_Minnons_GitHub-2](https://user-images.githubusercontent.com/628590/79692326-74562600-8232-11ea-9719-6928b1e5c754.png)

**Comment by KadeejaBai** [comment]
Please install the dependencies 
 1. Navigate to the folder com.lightning.tictactoeminion.game 
 2. Execute the command 'npm i' 
 3. Then lng build and lng serve 
 The App will open up in your chrome browser
